config/routes.rb
SampleApp::Application.routes.draw do
   
  resources :events
  resources :users
  resources :holidays
  resources :sessions, only: [:new, :create, :destroy] 
  root to: 'static_pages#home' 
  match '/signup',  to: 'users#new' 
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/create' , to: 'events#new' 
  match '/edit:id', to: 'events#edit'
  match '/index' , to: 'events#index'
  match '/users/:id' + :month.to_s, to: 'users#show'
  match '/holidays/:id' , to: 'holidays#show'
  match '/holidays/new' , to: 'holidays#new'
  match '/holidays/edit/:id' , to: 'holidays#edit'
  
  
  
 
  
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
 
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Rudy on Rails", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
        	 
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Logged in as <%=   current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li> <%= link_to "Create Event", '/create' %></li>
                
                  <li> <%= link_to "All Events", '/index' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <title>_shim.html</title>
	  <%= javascript_include_tag :defaults %>
	  <%= yield :head %>
  </head>
  <body>
  <%= yield %>
  </body>
</html>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
 
  
  
    <%= stylesheet_link_tag    "application", media: "all" %>
    
    <%= javascript_include_tag "application" %>
 

    <%= csrf_meta_tags %>
    
 
   

      <%= yield %>
      <div class="push"></div>
      </div>

         </div> 


 
           </div> 
</div>
  
          
            

      



  


  </body>
  





</html>